### ISSUE TITLE
typo in post "indieweb link sharing"

### ISSUE THREAD

**Issue by binyamin** [maxboeck/mxb#37]
https://github.com/maxboeck/mxb/blob/0e22a11fe7c3f647e1c00208a2149dbe9b39bf10/src/posts/indieweb-link-sharing/2019-08-11-index.md#L71-L73

The link for the full script points to "/_lambda/share.js", but the path has changed to "/lambda/share.js".

Have a great day!

**Comment by maxboeck** [comment]
@binyamin  thanks for the hint - fixed!
