### ISSUE TITLE
Curious about monitization

### ISSUE THREAD

**Issue by inetbiz** [maxboeck/mxb#75]
```<meta name="monetization" content="$ilp.uphold.com/7qZLaNKjDa87">```
What is uphold about and how can I use it?

**Comment by bzerangue** [comment]
Web Monetization is being proposed as a W3C standard at [the Web Platform Incubator Community Group](https://github.com/WICG/webmonetization). You can find out more about it, https://webmonetization.org/.

**Comment by inetbiz** [comment]
I know all of that, but the URL is what I asked about.

---
Denver Prophit Jr.
DPCG, Co. - Front End Developer
Tel: +1 386-314-3502 Cell

This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this email. Please notify the sender
immediately by e-mail if you have received this email by mistake and delete
this email from your system. E-mail transmission cannot be guaranteed to be
secure or error-free as information could be intercepted, corrupted, lost,
destroyed, arrive late or incomplete, or contain viruses. The sender
therefore does not accept liability for any errors or omissions in the
contents of this message, which arise as a result of e-mail transmission.
If verification is required please request a hard-copy version. Denver
Prophit Jr., 1336 Cr 459 #47A, Lake Panasoffkee FL, USA 33538,
www.denverprophit.us

**Comment by maxboeck** [comment]
@inetbiz the URL points to a digital wallet that can receive micro-transactions. When I first looked into this, Uphold was the only provided who offered support for the Interledger protocol. There may be others now.
