### ISSUE TITLE
hfeed

### ISSUE THREAD

**Issue by inetbiz** [maxboeck/mxb#76]
https://github.com/maxboeck/mxb/blob/6b4c45d9fb40ceb79ccd99d4b26c3b75ea9b8d5f/src/layouts/base.njk#L26

I saw nothing in this code area that generates a feed. Is this a bug?

**Comment by bzerangue** [comment]
@inetbiz - this is not a bug, @maxboeck is utilizing [Microformats](https://microformats.org/), it is a way of marking up your HTML.

**Comment by inetbiz** [comment]
I know that. But,  if you look at the span layer, there is no feed there.

---
Denver Prophit Jr.
DPCG, Co. - Front End Developer
Tel: +1 386-314-3502 Cell

This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this email. Please notify the sender
immediately by e-mail if you have received this email by mistake and delete
this email from your system. E-mail transmission cannot be guaranteed to be
secure or error-free as information could be intercepted, corrupted, lost,
destroyed, arrive late or incomplete, or contain viruses. The sender
therefore does not accept liability for any errors or omissions in the
contents of this message, which arise as a result of e-mail transmission.
If verification is required please request a hard-copy version. Denver
Prophit Jr., 1336 Cr 459 #47A, Lake Panasoffkee FL, USA 33538,
www.denverprophit.us

**Comment by maxboeck** [comment]
@inetbiz per the microformats wiki: 

> h-feed is a simple, open format for publishing a stream or feed of [h-entry](https://microformats.org/wiki/h-entry) posts, like complete posts on a home page or archive pages, or summaries or other brief lists of posts. h-feed is one of several open microformat draft standards suitable for embedding data in HTML.

https://microformats.org/wiki/h-feed

the homepage, blog index or note index page each qualifies for this. I guess it could be moved out of the base layout though.
